### ISSUE TITLE
Calibration design issue

### ISSUE THREAD

**Issue by ranjitkathiriya544** [facebookresearch/ocean#41] opened 2024-10-02 14:42 UTC
Thanks for the reply, 

1. In pattern calibration, if the pattern is too far from the camera, the calibration will not work effectively.
2. I have observed that for an image to be detected, more than 80% of the frame should be occupied by the pattern. If it’s less, detection fails.

I have added an example of a patten below, that might failed in scenario. 

![a](https://github.com/user-attachments/assets/3af1f0e3-2761-435d-87e0-e2835835f856)

what I have observed, that if you crop a image, in below way then I can be able to detect. That's proofs 2 point.

![image](https://github.com/user-attachments/assets/c2309668-374f-478c-8f44-4b20193de2ff)

_Originally posted by @ranjitkathiriya544 in https://github.com/facebookresearch/ocean/issues/40#issuecomment-2384135730_

**Comment by leapally** [comment] 2024-10-02 20:45
Hi, @ranjitkathiriya544.

Are you able to move the calibration pattern closer to the camera or print a larger calibration pattern?  Could you explain your use case?  Maybe that would help us understand the need to have a calibration pattern that takes up a small portion of the camera's field of view.

I'm not terribly familiar with Ocean's square array pattern calibration process, but I imagine that calibration pattern taking up a large portion of the field of view of the camera is desirable.  So the behavior you observed may be intentional and true to design rather than a bug.

**Comment by ranjitkathiriya544** [comment] 2024-10-03 09:32
our camera and the pattern distance is 2.6 meters, and also the maximum size of pattern A1. 

With OpenCV it works fine, we are comparing the both methods.

**Comment by ASchneiderMeta** [comment] 2024-10-04 22:54
I've been able to reproduce your problem with the large image you attached to the Issue. Unfortunately, it turns out that Ocean's calibration pattern detector is not very robust to visible edges that are not part of the pattern itself. If I start with the large image you attached to this issue and use gimp to fill the red background (and the "Scene" text) with white, the pattern is detected successfully and the code you posted in your now-closed issue seems to work, after correcting the number of columns to 3.
For a quick fix, if it's possible to put the calibration pattern in front of a quiet white background, the detector is likely to work better. We will work on making the detector more robust and hope to have an improvement for you next week.

**Comment by leapally** [comment] 2024-10-07 18:24
Hi @ranjitkathiriya544,

Could you share with us the field of view and resolution figures for your camera?

And is this an RGB camera or monochrome?  And is there anything special about the lighting conditions or objects visible in the background?

**Comment by ASchneiderMeta** [comment] 2024-10-08 22:12
Hi, @ranjitkathiriya544, commit f41f9bd401514f5c424c3f983fe547ecfad819a4 just landed. It fixes an oversight in the configuration of calibration pattern detection and your example images now work for me. If you have a chance to try it out, please let us know how it goes!

**Comment by ranjitkathiriya544** [comment] 2024-10-09 12:56
> Could you share with us the field of view and resolution figures for your camera?

180 - 185 degree fov, an fisheye camera. 

> And is this an RGB camera or monochrome?

RGB camera.

> And is there anything special about the lighting conditions or objects visible in the background?

Not much, just a normal environment with a cool light.

@ASchneiderMeta, thanks, it's works, for the image which I uploaded, but, if I twist the image by adding more corners and colours, it got failed, I am looking for an robust solution. Try this below image, this got failed. 

 
![372251138-3af1f0e3-2761-435d-87e0-e2835835f856 (1)](https://github.com/user-attachments/assets/db3c1db8-22d3-4ccc-b9a0-e8facf7e17cd)

In OpenCV if there are multiple patterns, it detect one, but doesn't failed the patten detection. In Ocean, it fails to detect any patten. Hence, we cannot use for multi patten exist. 

![c](https://github.com/user-attachments/assets/d3b2b004-e241-4981-91fb-6d53015c107a)

**Comment by ASchneiderMeta** [comment] 2024-10-09 17:56
The current calibration pattern detector depends on a strong assumption that a single coherent calibration pattern dominates the scene. Providing exactly what you're looking for is probably a larger project than we can take on right now.
In principle, one larger coherent pattern could be manually constructed from separate sheets taped to a wall in prescribed positions, but I understand that's a lot of work and might not be practical at all for you.

**Closed** 2024-10-14 17:24 UTC
